### PR TITLE
Make Wharton Python Vagrant work with Learning Lab SIMPL

### PR DESCRIPTION
**Pull request by frankwiles**
Hello! 

For learning lab to use this Vagrant we needed a couple of extra things: 

- PostgreSQL 9.6
- Port 8080 and 8100 open 

These changes, you know, do that.

### CODE REVIEW

**Comment by FlipperPA** [comment]
Thanks for the PR, @frankwiles - we had kept the PostgreSQL install to a script so it was optional, and available as `assets/install_postgres.sh`. However, I'm thinking since it isn't a huge time sink to install as a package, we may as well just do it, especially since I forget to every time I stand up a fresh Vagrant box.

I note that you're installing `python-psycopg2` - isn't this from RedHat/CentOS, and horribly out of date? Would it be worth just creating a symlink to `pg_config` so anyone can `pip install psycopg2` and get a newer version, like we do here?

https://github.com/wharton/python-vagrant-centos7/blob/master/assets/install_postgres.sh#L17

**Comment by FlipperPA** [comment]
I'm going to go ahead and merge this and add the symbolic link.

**Comment by frankwiles** [comment]
Hey Tim, 

Yeah the `python-psycopg2` is old and out of date, but necessary for Ansible to setup the `vagrant` user in PG.  In practice, we tend to use virtualenvs inside Vagrant so it won't get in the way of anything.

**Comment by FlipperPA** [comment]
Perfect. I also noticed it isn't that out of date - it actually installs from the `pdgd96` repository via yum rather than RedHat, which is what I worried about. `2.7.1` is fairly current. I'm adding the symlink to avoid "Could not find pg_config" errors during the pip install.

**Pull request merged**
